### ISSUE TITLE
您好，请问您们论文里面关于HARDVS数据集里面的准确率与HARDVS自己官方论文给出的准确率相差了几十个点，这是什么原因导致的？

### ISSUE THREAD

**Issue by gshaowei6** [QiWang233/DailyDVS-200#11]
您好，请问您们论文里面关于HARDVS数据集里面的准确率与HARDVS自己官方论文给出的准确率相差了几十个点，这是什么原因导致的？

**Comment by QiWang233** [comment]
Hi,
We think it is caused be the data preprocession, you can get more information in the paper.
