### ISSUE TITLE
您好，我目前正在嘗試訓練swin-transformer，但以我目前的實驗設定僅能達到top-1 acc. 46.44%，因此想向您請教應該要如何調整訓練參數

### ISSUE THREAD

**Issue by Bacon9629** [QiWang233/DailyDVS-200#12]
我目前正在嘗試複現您的swin-transformer的實驗數據，我使用repo內的mmaction2框架與config [swin-base-p244-w877_in1k-pre_8xb8-amp-32x2x1-30e_kinetics400-rgb.py](https://github.com/QiWang233/DailyDVS-200/blob/main/models/mmaction2_lastest/configs/recognition/swin/swin-base-p244-w877_in1k-pre_8xb8-amp-32x2x1-30e_kinetics400-rgb.py)進行訓練，但僅能達到top-1 acc. 46.44%，而論文上數據是48.06%，因此想向您詢問是否有甚麼參數是需要進行修改的呢？

**Comment by QiWang233** [comment]
Hi,
We also directly used the repo in mmaction2, you can refer to the config parameters in our repo.
