### ISSUE TITLE
DailyDVS-200d的.txt文件

### ISSUE THREAD

**Issue by wsasdsda** [QiWang233/DailyDVS-200#2]
您好，感谢您在ECCV上提供的 DailyDVS-200数据集。我想请问训练和测试的.txt文件是怎么划分的，我们最近在DilyDVS-200数据集上跑自己的方法，希望能分享一下！

**Comment by QiWang233** [comment]
there will be an update coming soon

**Comment by wsasdsda** [comment]
感谢！

**Comment by wsasdsda** [comment]
> there will be an update coming soon

感谢！

**Comment by QiWang233** [comment]
Done
