### ISSUE TITLE
DailyDVS-200 on Hugging Face

### ISSUE THREAD

**Issue by merveenoyan** [QiWang233/DailyDVS-200#6]
Hello @QiWang233  🤗

I'm Merve and I work on computer vision at Hugging Face. I see your paper is accepted as ECCV Posters congratulations! I indexed it here https://huggingface.co/papers/2407.05106 at paper pages. The paper page lets people discuss about your paper and lets them find artifacts about it (your dataset for instance) you can also claim the paper as yours which will show up on your public profile at HF.

Would you like to host the datasets https://huggingface.co/datasets?  Hosting on Hugging Face will give your work more visibility.

After uploaded, we can also link the datasets to the paper page (read [here](https://huggingface.co/docs/hub/en/model-cards#linking-a-paper)) so people can discover your dataset.

What do you think?

**Comment by QiWang233** [comment]
Hi, 

That would be great, I'd like to take on this work.
