### ISSUE TITLE
Request for Access to Preprocessed Training Dataset for Consistent Research Extension

### ISSUE THREAD

**Issue by Bacon9629** [QiWang233/DailyDVS-200#7]
Hello,

In #4, you mentioned that when training the Swin Transformer, you referred to the preprocessing method used in HARDVS to prepare the training data for DailyDVS.

We are actually looking to extend our work using your dataset, and to ensure consistency in our training standards, we would prefer to use the same preprocessed training dataset that you used for training the Swin Transformer.

If you could kindly provide the preprocessed training dataset, I would be extremely grateful. Additionally, I assure you that we will appropriately cite your work in any future publications.

Thank you very much for your time and consideration.

**Comment by QiWang233** [comment]
Hello,

Actually it was the frame-based way to create the image sequences, the only variable contant is the interval to create the image. In our work, inteval is 0.5s. Maybe this is what you want. 

The code is very easy, so you can easily handle it.

**Comment by QiWang233** [comment]
Hi,

The label file you want have been updated, if you have any questions, please contact me in time.

**Comment by Bacon9629** [comment]
Hello, thank you for your reply.

Regarding the dataset preprocessing part, I really appreciate the information you provided! The preprocessing code you're using is the EventImageConvert._events_to_event_images function from utils/event_image_convert.py, and I can apply a 0.5-second interval there to use it, right?

If that's the case, it would indeed be more convenient for me to handle this on my own.

As for the label file, it seems that the permission for the Google Drive link hasn't been granted. Could you please check it?

**Comment by QiWang233** [comment]
Hi,

That is correct!
you can try this url for label：https://drive.google.com/file/d/1Eod6eO7EB8qHBDCpX11mClUnYczbXNwp/view.

**Comment by Bacon9629** [comment]
Hello

When I clicked on your link, I encountered this page. I’ve already requested access, could you kindly check again?
![image](https://github.com/user-attachments/assets/7fd3619f-2c5a-4933-81c4-13183019ad96)

**Comment by QiWang233** [comment]
Hi,

Sorry！I forgot that, it has been done.

**Comment by Bacon9629** [comment]
I can now access the document! Thank you very much!
