### ISSUE TITLE
时间戳长度问题

### ISSUE THREAD

**Issue by hanyf0404** [QiWang233/DailyDVS-200#8]
您好，请问在aedat4文件中，时间戳长度多少为一帧呢？

**Comment by QiWang233** [comment]
Hi,

I think your question is about the time resolution of timestamp. Here is the information:

<img width="953" alt="1728462424492" src="https://github.com/user-attachments/assets/9c3ce890-fade-4efa-9529-a259b00cc8a0">

**Comment by hanyf0404** [comment]
感谢您的解答，
我想请教一下，现在每个aedat4文件中存储的信息包含一定数量的时间戳，我想把这些事件信息转换为event image时，多少长度时间戳可以作为一张图呢？

**Comment by hanyf0404** [comment]
我看到event_image_convert.py 文件中有一个interval 参数，请问是否和这个参数有关呢，这个参数在这个数据集上应该设置为多少呢？
十分感谢

**Comment by Bacon9629** [comment]
您好
我想您可以參考 #7 ，那邊作者有提到在DailyDVS-200上是使用0.5sec

**Comment by hanyf0404** [comment]
您好，
请问这个interval是设置为0.5吗，我按照0.5处理的很多时间相机图，发现信息很模糊
![00000010](https://github.com/user-attachments/assets/1e63df71-86bf-4d90-abb9-23c78a062240)
例如这一种

**Comment by hanyf0404** [comment]
还有这些也很模糊
![00000007](https://github.com/user-attachments/assets/324fc767-14f0-4d9d-9ad1-927471751073)
想问下我看到event_image_convert函数中默认得interval长度为0.25，所以想和您确认一下，
十分感谢

**Comment by QiWang233** [comment]
Hello,

I believe it is normal with event camera data, so I'm not sure about your specific concern. However, if you only intend to use the event frame, a duration of 0.5 seconds should be sufficient. Perhaps you can conduct more experiments.

**Comment by hanyf0404** [comment]
您好，
我看到文章中用该数据集测试了一些frame based的方法，所以想问下这些方法在测试时，interval这个参数设置的是多少呢？

**Comment by QiWang233** [comment]
Hi,

I believe it was mentioned in our paper. It is a duration of 0.5 seconds for frame-based methods.

**Comment by hanyf0404** [comment]
好的，十分感谢！
