### ISSUE TITLE
Missing train/val/test.txt in the Google Drive version

### ISSUE THREAD

**Issue by newflw** [QiWang233/DailyDVS-200#9]
Hello,
I am trying to access the split files but I am only able to access the Google Drive version. Could you perhaps add those split files to the repo or add it in the Google Drive version as well?

**Comment by QiWang233** [comment]
Hi,

You can access those files in the repo now!

**Comment by newflw** [comment]
Thanks!
The paths in those files do not match exactly with the paths in the Google Drive zip files, but it is no big deal. Good to know about anyway.
Cheers!
